name: semantic-communication
channels:
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - transformers
  - scikit-learn
  - matplotlib
  - nltk
  - numpy
  - tqdm
  - w3lib
