name: semantic-communication
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytorch::pytorch
  - torchaudio
  - torchvision
  - scikit-learn
  - transformers
  - numpy
  - pandas
  - openpyxl
  - scipy
  - tqdm
  - pip
  - pip:
      - openai
      - bert-score
      - sentence-transformers
